version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: blackbox
      POSTGRES_PASSWORD: blackbox
      POSTGRES_DB: blackbox
    ports:
      - "5432:5432"
    volumes:
      - blackbox_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - blackbox_redisdata:/data

volumes:
  blackbox_pgdata:
  blackbox_redisdata:
